### ISSUE TITLE
Review islandora_context to see if it can be used for annotations

### ISSUE THREAD

**Issue by Natkeeran** [digitalutsc/islandora_web_annotations#1]
Ideally, we want annotations to be displayed as add-ons to existing objects such as an image, video, audio or pdf.  

We need to look at ways to manipulate an object's display without having a custom content model or custom viewer.  We also want to add controls to the object that user can interact with.  

@MarcusBarnes pointed out that https://github.com/mjordan/islandora_context could be useful.  This ticket is to review that module and see if it can be used for the above stated purposes.

**Comment by MarcusBarnes** [comment]
Prototypes by @Natkeeran indicate that https://github.com/mjordan/islandora_context is helpful.  To be determined if islandora_context would be a required.
