### ISSUE TITLE
Create an abstraction layer to make ajax calls to backend

### ISSUE THREAD

**Issue by Natkeeran** [digitalutsc/islandora_web_annotations#10]
Currently, the initial prototype has the create,  update, delete and load/get ajax calls in the large_image.js.  These ajax calls will be similar or same for other content types as well.  These calls can be abstracted out into its own js so it can be used by other content types to interact with the backend.

**Comment by MarcusBarnes** [comment]
Initially addressed in pull-request https://github.com/digitalutsc/islandora_web_annotations/pull/19 (merged with commit https://github.com/digitalutsc/islandora_web_annotations/commit/3b9d1c50cc1bd465b40e7d33c064b3467514a78d).
