### ISSUE TITLE
AnnotationContainer: Provide ability to configure qualifier prefix

### ISSUE THREAD

**Issue by MarcusBarnes** [digitalutsc/islandora_web_annotations#101]
The prefix used in `$qualifier` at https://github.com/digitalutsc/islandora_web_annotations/blob/7.x/includes/AnnotationContainer.php#L246 may not always be available.  Provide an admin setting to provide a means set this appropriately for a given install.

**Comment by Natkeeran** [comment]
This PR addresses this issue: https://github.com/digitalutsc/islandora_web_annotations/pull/96

**Comment by MarcusBarnes** [comment]
Initial work in pull-request https://github.com/digitalutsc/islandora_web_annotations/pull/104 - waiting for review.

**Comment by Natkeeran** [comment]
Works as expected.  Thanks Marcus.
