### ISSUE TITLE
Delete annotation message

### ISSUE THREAD

**Issue by Natkeeran** [digitalutsc/islandora_web_annotations#102]
There is a minor bug in alerting a message when an annotation is delete: 
https://github.com/digitalutsc/islandora_web_annotations/blob/7.x/js/base/base.js#L272

## Steps to reproduce
* Delete an annotation - no message is shown, a message should be shown

**Comment by MarcusBarnes** [comment]
Addressed in commit https://github.com/digitalutsc/islandora_web_annotations/commit/8ab6bd4dfbc7bc904e9d9003a12e9aaea3b2dd77.  Thank you @Natkeeran for spotting the issue and committing the fix..
