### ISSUE TITLE
Improve delete hook (should we still delete the annotation even if the annotation container is not found for an annotation?)

### ISSUE THREAD

**Issue by Natkeeran** [digitalutsc/islandora_web_annotations#105]
When a user deletes an annotation from Drupal, the islandora_web_annotations_islandora_object_alter gets fired.  It relies on AnnotationContainer having been properly indexed when it gets created, i.e RELS_EXT_isAnnotationContainerOf_uri_s field gets created.  (Note that this NOT indexing of annotation for search purposes and does not need any additional solr setup.)

During the hogarth testing, we had a situation where AnnotationContainer was not being indexed.  Thus, we could not delete the annotations!.  Should we still delete the annotation even if the annotation container is not found for an annotation?

**Comment by MarcusBarnes** [comment]
Addressed in pull-request https://github.com/digitalutsc/islandora_web_annotations/pull/141 (merged with commit https://github.com/digitalutsc/islandora_web_annotations/commit/cd29b63569cf130007dd992d1ff5df985dc18688).
