### ISSUE TITLE
HTML block changes and add back to codebase

### ISSUE THREAD

**Issue by kstapelfeldt** [digitalutsc/islandora_web_annotations#106]
As per the unit meeting today:

Add HTML block back into the codebase as an option, providing formatting for the numbers and increased space between annotations (improve readability of HTML block). I have in my notes to assign this to Marcus, but feel free to change :) Let me know if you want me to review.

**Comment by MarcusBarnes** [comment]
Addressed in pull-request https://github.com/digitalutsc/islandora_web_annotations/pull/111 (merged with commit https://github.com/digitalutsc/islandora_web_annotations/commit/4919b6251361486230797bfdcbdcced3aacabd98).
