### ISSUE TITLE
Configuration option - load annotations by default

### ISSUE THREAD

**Issue by kstapelfeldt** [digitalutsc/islandora_web_annotations#107]
Wondering how hard it would be to create a configuration option for annotations to appear loaded by default.

**Comment by MarcusBarnes** [comment]
I've done some initial investigation.  Thanks to @Natkeeran's nice JS code I should be able to push a branch for testing soon.

**Comment by kstapelfeldt** [comment]
Awesome!

**Comment by MarcusBarnes** [comment]
Initial work on this is in branch https://github.com/digitalutsc/islandora_web_annotations/tree/issue-107 - works great for large image, but there are still some adjustments needed for basic image.

**Comment by Natkeeran** [comment]
https://github.com/digitalutsc/islandora_web_annotations/pull/118 addresses this issue.
