### ISSUE TITLE
Annotation in HTML block non-expected behaviour

### ISSUE THREAD

**Issue by kstapelfeldt** [digitalutsc/islandora_web_annotations#108]
This occurred as Chad and I were testing simultaneous editing. I created an annotation that was numbered. Then I edited it and it changed as depicted in the attached screenshot
![screen shot 2017-02-23 at 2 04 11 pm](https://cloud.githubusercontent.com/assets/467898/23274548/221660ea-f9d1-11e6-85b6-540de3d838d6.png)

**Comment by Natkeeran** [comment]
I think this was due to not properly updating the block item when it gets edited.  Should be addressed with this PR: https://github.com/digitalutsc/islandora_web_annotations/pull/111

**Comment by MarcusBarnes** [comment]
Addressed in pull-request https://github.com/digitalutsc/islandora_web_annotations/pull/111 (merged with commit https://github.com/digitalutsc/islandora_web_annotations/commit/4919b6251361486230797bfdcbdcced3aacabd98).
