### ISSUE TITLE
Simultaneous editing issue

### ISSUE THREAD

**Issue by kstapelfeldt** [digitalutsc/islandora_web_annotations#109]
As two people seek to annotate the same object, we expect the following behaviour:

1. User one creates annotation and receives confirmation message 
2. User two creates annotation and receives confirmation message
3. Either user would refresh the page and see the annotation created by the other. 

Instead, Annotations created by the other user do not load, and on refresh, fail to load for the original user. Please let me know if you need additional details to reproduce.

**Comment by MarcusBarnes** [comment]
Initial work addressing this issue is added with commit https://github.com/digitalutsc/islandora_web_annotations/commit/076b57b97db1a024f8528ba319fd3dd4c3ce0085.

**Comment by MarcusBarnes** [comment]
The prior work in commit 076b57b appears to be functioning as expected - closing this issue.
