### ISSUE TITLE
After updating an annotation, the edit, delete buttons are hidden

### ISSUE THREAD

**Issue by Natkeeran** [digitalutsc/islandora_web_annotations#110]
## Steps to reproduce
* As an authenticated use create an annotation
* Edit an annotation
The edit and delete buttons are hidden.  If I created it, the it show show.

## Technical Notes
* We are not updating the permissions information (creator) properly after an annotation gets updated.

**Comment by MarcusBarnes** [comment]
Addressed in pull-request https://github.com/digitalutsc/islandora_web_annotations/pull/112 (merged with commit https://github.com/digitalutsc/islandora_web_annotations/commit/bf54e06740c6710ba96072fe4a5daca9bb09deed).
