### ISSUE TITLE
Basic Image:  Load annotation button shifts when user is not admin

### ISSUE THREAD

**Issue by MarcusBarnes** [digitalutsc/islandora_web_annotations#113]
For basic images, the annotation buttons are shifted down for an authenticated user as compared to when the user has an administrator role.   Some CSS adjustments may need to be made.  See the images below:

Basic Image - annotation buttons for an authenticated user (non-administrator):
![image](https://cloud.githubusercontent.com/assets/938274/23313170/9f3fc944-fa8a-11e6-9c46-8fcd295dd392.png)

Basic Image - annotation buttons for an administrator:
![image](https://cloud.githubusercontent.com/assets/938274/23313228/d0bee676-fa8a-11e6-8030-9e0aac79cce1.png)

**Comment by Natkeeran** [comment]
https://github.com/digitalutsc/islandora_web_annotations/pull/120 addresses this issue.
