### ISSUE TITLE
Import WADCContainer and WADC Content Models upon install

### ISSUE THREAD

**Issue by Natkeeran** [digitalutsc/islandora_web_annotations#12]
The annotations models need WADCContainer and WADC Content Models to be in the fedora to work.  These need to be installed when the module gets installed, similar to how Oral Histories module installs WADC Content Model.

**Comment by Natkeeran** [comment]
[PR#17](https://github.com/digitalutsc/islandora_web_annotations/pull/17) does provide functionality to import the required objects.  However, the exact hook/method to import is yet to be finalized.

**Comment by MarcusBarnes** [comment]
Addressed in pull-request https://github.com/digitalutsc/islandora_web_annotations/pull/38 (committed in https://github.com/digitalutsc/islandora_web_annotations/commit/2cdda132890390deaa0db5c3fa024a3e10991f9d).
