### ISSUE TITLE
Hiding Clip Image tool for large image

### ISSUE THREAD

**Issue by MarcusBarnes** [digitalutsc/islandora_web_annotations#121]
Some users have reported that they would like to be able to hide the Clip Image tool that appears when using the Open Seadragon viewer used with large image annotations.

![image](https://cloud.githubusercontent.com/assets/938274/23528332/7dd963a0-ff67-11e6-8786-505fda508f29.png)

This may best be addressed as an enhancement to  [Islandora OpenSeadragon](https://github.com/Islandora/islandora_openseadragon).   It may be useful to provide a way to do this either within Islandora Web Annotations code or in the documentation plus a gist until it becomes available as a viewer configuration option.

**Comment by MarcusBarnes** [comment]
Following up to my [previous comment](https://github.com/digitalutsc/islandora_web_annotations/issues/121#issue-211528405),  the clipper is actually created in the [large image solution pack](https://github.com/Islandora/islandora_solution_pack_large_image) code.  Islanodra OpenSeadragon only makes some adjustments to the clipper.

**Comment by Natkeeran** [comment]
https://github.com/digitalutsc/islandora_web_annotations/pull/122 addresses this issue.
