### ISSUE TITLE
Updating a video annotation right after creating it

### ISSUE THREAD

**Issue by Natkeeran** [digitalutsc/islandora_web_annotations#123]
Creating, then reloading and uploading a video annotation works as expected.  However, if an annotation is created, and updated right after, it is failing.

**Comment by MarcusBarnes** [comment]
Addressed in pull-request https://github.com/digitalutsc/islandora_web_annotations/pull/128 (merged with commit https://github.com/digitalutsc/islandora_web_annotations/commit/96bdece084f113d9921220a25e4dc621dc414b62).
