### ISSUE TITLE
Improve error checking when CRUD operations for video fail cases

### ISSUE THREAD

**Issue by Natkeeran** [digitalutsc/islandora_web_annotations#127]
Currently the error checking of CRUD operations is failing.  For example, it is returning successful, even if it fails!

**Comment by Natkeeran** [comment]
This PR addresses this issue: https://github.com/digitalutsc/islandora_web_annotations/pull/140

**Comment by MarcusBarnes** [comment]
Addressed in pull-request https://github.com/digitalutsc/islandora_web_annotations/pull/140 (merged with commit https://github.com/digitalutsc/islandora_web_annotations/commit/1dc49188da8ed1e1443375cdf8b7a34ec1830057).
