### ISSUE TITLE
Interation 1 php refactoring/code cleanup

### ISSUE THREAD

**Issue by Natkeeran** [digitalutsc/islandora_web_annotations#13]
* Re-factor to extract constants
* Add UUID to annotation and annotationContainer
* Add error handling
* Improve return json to conform more to the Annotation Protocol
* Add comments
* Add a Util class to handle static methods
* Clean up controller and method signatures

**Comment by MarcusBarnes** [comment]
Initial work on these points have been added as of commit https://github.com/digitalutsc/islandora_web_annotations/commit/3b9d1c50cc1bd465b40e7d33c064b3467514a78d.  As appropriate, please create new issues for further work and refinement on the items in the list.
