### ISSUE TITLE
Default Open Video Annotation permissions checkboxes showing in video annotation pop-up

### ISSUE THREAD

**Issue by MarcusBarnes** [digitalutsc/islandora_web_annotations#130]
The default Open Video Annotations permission checkboxes are showing in the annotation pop-ups when creating video annotations.  We are not using this feature (rather, using the Drupal permission layer).  These checkboxes should not be displayed.

![image](https://cloud.githubusercontent.com/assets/938274/23858038/a14eff04-07d5-11e7-9590-0e5988133b31.png)

**Comment by Natkeeran** [comment]
This PR resolves that issue: https://github.com/digitalutsc/islandora_web_annotations/pull/131
