### ISSUE TITLE
Provide warning when annotation is being deleted (are you sure)

### ISSUE THREAD

**Issue by kstapelfeldt** [digitalutsc/islandora_web_annotations#132]
to discuss as possible enhancement: 

"This annotation will be deleted. This action cannot be reversed. Are you sure?"

**Comment by kimpham54** [comment]
when no verbose messaging is turned on

1. I create an annotation —> Save/Cancel
2. Annotation is created --> no message
3. I edit an annotation --> Save/Cancel
4. Annotation is edited --> no message
5. I delete an annotation —> “are you sure (yes/no)” - yes and annotation is deleted, no, and it is not deleted.
6. Annotation is deleted —> no message

when verbose messaging is activated

1. I create an annotation —> Save/Cancel
2. Annotation is created --> confirmation + JSON output
3. I edit an annotation --> Save/Cancel
4. Annotation is edited --> confirmation + JSON output
5. I delete an annotation —> This annotation will be deleted. This action cannot be reversed. Are you sure?” with “Delete” and “cancel” as the buttons
6. Annotation is deleted —> confirmation, PIDs of deleted objects

**Comment by kstapelfeldt** [comment]
Shouldn't #5 for "no verbose messaging" match #5 for "verbose messaging"? ...suggested edit:

when no verbose messaging is turned on

I create an annotation —> Save/Cancel
Annotation is created --> no message
I edit an annotation --> Save/Cancel
Annotation is edited --> no message
I delete an annotation —>" This annotation will be deleted. This action cannot be reversed. Are you sure?” with “Delete” and “Cancel” as the buttons
Annotation is deleted —> no message

when verbose messaging is activated

I create an annotation —> Save/Cancel
Annotation is created --> confirmation + JSON output
I edit an annotation --> Save/Cancel
Annotation is edited --> confirmation + JSON output
I delete an annotation —> "This annotation will be deleted. This action cannot be reversed. Are you sure?” with “Delete” and “Cancel” as the buttons
Annotation is deleted —> confirmation, PIDs of deleted objects

**Comment by Natkeeran** [comment]
Warning before delete is trickier to implement for video than expected because the 1.2.x production annotator js library that we are using does not provide a beforeAnnotationDelete event.  There is an un addressed issue related to this request in their github.  2.x beta release does include this event.

Currently exploring if we can add a workaround for this.

**Comment by kstapelfeldt** [comment]
Basic and Large image to be implemented for this release - Video will remain on the roadmap for the future.

**Comment by MarcusBarnes** [comment]
@kimpham54 Please review.  You'll need to update your contexts (see the wiki).

**Comment by kimpham54** [comment]
issue resolved with https://github.com/digitalutsc/islandora_web_annotations/pull/193
