### ISSUE TITLE
Need to add scroll bar to video annotation view/edit box

### ISSUE THREAD

**Issue by Natkeeran** [digitalutsc/islandora_web_annotations#135]
Currently, the video annotation view/edit box extends to the edge of the screen when the annotation is too long.  Add a scroll similar to image annotation.

**Comment by Natkeeran** [comment]
https://github.com/digitalutsc/islandora_web_annotations/pull/137 addresses this issue.

**Comment by MarcusBarnes** [comment]
Merged with commit https://github.com/digitalutsc/islandora_web_annotations/commit/231a37ab666b565da6c7fd16ff95a83aa0065e40.
