### ISSUE TITLE
Video annotation text should be normal

### ISSUE THREAD

**Issue by Natkeeran** [digitalutsc/islandora_web_annotations#136]
When video annotation is moused over and viewed, the text is italic.  Make it normal.

**Comment by Natkeeran** [comment]
@kstapelfeldt I don't see the video annotations to be italic by default.  Please provide the steps to reproduce this issue.

**Comment by kstapelfeldt** [comment]
Kirsta cannot reproduce on the newest version that we are testing for release. Closing for now.
