### ISSUE TITLE
PHP Parse error in AnnotationController

### ISSUE THREAD

**Issue by bencomp** [digitalutsc/islandora_web_annotations#138]
After installing this module in an Islandora 1.7 installation, including replacing OpenSeadragon, configuring the Large Image context and updating the Solr schema and GSearch indexing operations and restarting Tomcat, I get errors when loading annotations or trying to create annotations for a large image with PID `item:13`. In Apache's error log I see:

```
PHP Parse error:  syntax error, unexpected '[' in /var/www/html/drupal7/sites/all/modules/islandora_web_annotations/includes/AnnotationController.php on line 63
```

This happens when I request, e.g., `https://ISLANDORA/islandora_web_annotations/get?targetPid=item:13`. The result is an empty page that comes with HTTP 500 Internal Server Error.

Looking at [AnnotationController.php#L63](https://github.com/digitalutsc/islandora_web_annotations/blob/7.x/includes/AnnotationController.php#L63), I notice that `$arrResult` is not defined before – I wonder if this is related to the error?

We run PHP 5.3.3.

**Comment by MarcusBarnes** [comment]
@bencomp  We've updated Travis to check against PHP 5.3 to help catch this kind of syntax issue going forward.  Please pull the latest from the default branch.  We look forward to your feedback.  Thank you in advance.
