### ISSUE TITLE
Error with simultaneous add of annotations

### ISSUE THREAD

**Issue by kimpham54** [digitalutsc/islandora_web_annotations#145]
Description
Error occurs when two users try to simultaneously add annotations in Simple Image

Authenticateduser1 Authenticateduser2 Synchronous web annotation add simple image

Two users add an annotation at the same time (ideally, the first annotation on an object)	

Expected Behaviour
Both Annotations are successfully created. 

Actual behaviour: In the first instance, When Kirsta and I tried to save at the same time:
Kim - error message
Kirsta - no message, but annotation appears. 10s lag in sending, then error message appears.
Kirsta - click on view annotations, annotation appears. on refresh and load, annotation disappears
does not always happen - in subsequent times, one person gets a delayed confirmation message"
Error message

Type  Islandora Web Annotations
Date  Tuesday, April 4, 2017 - 15:51
User  non2
Location  http://138.51.189.166:8000/islandora_web_annotations/create
Referrer  http://138.51.189.166:8000/woods/claw-chimera
Message Error in AnnotationTracker -> pollSolr: Timeout Exception. Taking too long to find solr index of the AnnotationContainer for target object with PID claw-chimera
Severity  error
Hostname  138.51.186.255
Operations

Type  Islandora Web Annotations
Date  Tuesday, April 4, 2017 - 15:51
User  non2
Location  http://138.51.189.166:8000/islandora_web_annotations/create
Referrer  http://138.51.189.166:8000/woods/claw-chimera
Message Error in createAnnotation: Timeout Exception. Taking too long to find solr index of the AnnotationContainer for target object with PID claw-chimera
Severity  error
Hostname  138.51.186.255

We have not been able to reproduce the issue since - please close if you cannot recreate this issue.

**Comment by kstapelfeldt** [comment]
We were not able to reproduce yesterday. @MarcusBarnes and @Natkeeran will try to reproduce

**Comment by kimpham54** [comment]
closing this ticket because we did not reproduce this issue in our testing today
