### ISSUE TITLE
Please change hover text for "load annotation" button

### ISSUE THREAD

**Issue by kstapelfeldt** [digitalutsc/islandora_web_annotations#147]
Should read "toggle annotation" to reflect the functionality provided by the button.

**Comment by MarcusBarnes** [comment]
Addressed in pull-request https://github.com/digitalutsc/islandora_web_annotations/pull/168 (merged with commit https://github.com/digitalutsc/islandora_web_annotations/commit/8d84716874620434fd2435b91a77e42ff7a6becb).
