### ISSUE TITLE
Implement ETag/If-Match based check before update/delete

### ISSUE THREAD

**Issue by Natkeeran** [digitalutsc/islandora_web_annotations#15]
Web Annotation Protocol requires an ETag to be checked before updating or deleting an annotation.  ETag is generated by the server (https://tools.ietf.org/html/rfc7232#section-2.3.1).  Checksum, version or timestamp could be used an as ETag.  The request must include the ETag in the "If-Match" header parameter when making the request.  Example from https://www.w3.org/TR/annotation-protocol/#update-an-existing-annotation.

```
PUT /annotations/anno1 HTTP/1.1
Host: example.org
Accept: application/ld+json; profile="http://www.w3.org/ns/anno.jsonld"
Content-Type: application/ld+json; profile="http://www.w3.org/ns/anno.jsonld"
Content-Length: 294
If-Match: "_87e52ce126126"

{
  "@context": "http://www.w3.org/ns/anno.jsonld",
  "id": "http://example.org/annotations/anno1",
  "type": "Annotation",
  "created": "2015-02-01T10:13:40Z",
  "body": {
    "type": "TextualBody",
    "value": "I REALLY like this page!"
  },
  "target": "http://www.example.com/index.html"
}
```

If the ETag has changed, then the request should not be processed.  An appropriate message should be returned tot the user.  User can choose to reload all annotations and try to preform the operation again.

**Comment by MarcusBarnes** [comment]
Initially addressed for basic image and large image with pull-request https://github.com/digitalutsc/islandora_web_annotations/pull/31 (merged with commit https://github.com/digitalutsc/islandora_web_annotations/commit/b0af4adffff84b44b2362159c5c8845145b80cd4).
