### ISSUE TITLE
Update configuration to emphasis importance of the setting The isAnnotationContainerOf Solr field 

### ISSUE THREAD

**Issue by MarcusBarnes** [digitalutsc/islandora_web_annotations#150]
Update setup documentation to emphasize the importance of the setting "The isAnnotationContainerOf Solr field" properly and hints on how to determine the correct value for new installations.

**Comment by kstapelfeldt** [comment]
@MarcusBarnes will add some documentation and reassign to @kimpham54 or me for testing to review.

**Comment by MarcusBarnes** [comment]
Some initial documentation -  https://github.com/digitalutsc/islandora_web_annotations/wiki/Configuration:-Setting-the-required-isAnnotationContainerOf-Solr-field-value, which is also linked to from the wiki table of contents.

**Comment by MarcusBarnes** [comment]
Maybe a part of this should be some troubleshooting documentation that includes tips on what to investigate when seeing certain types of issues based on our own and other's usage of the module?  Starting with one page would be a start and we could separate it into other pages within the wiki as appropriate.  Thoughts?
