### ISSUE TITLE
View-only permissions still allow create annotation actions (but does not write)

### ISSUE THREAD

**Issue by kimpham54** [digitalutsc/islandora_web_annotations#151]
Description
In the basic image content model, when a user is only allowed to view Annotations, the feather signpost that indicates to click and drag and the Click & Drag action is still enabled. A user is able to create an annotation, but it does not get saved (which is confusing).

Steps to Reproduce
1. In Permissions, only enable the View annotations, disable all other permissions in web annotations
2. Find a Basic Image content model object to create an annotation
3. Click on the View button, click and Drag to create an annotation

Expected Behaviour
User can view annotations in every content model, but cannot begin create an annotation or save an annotation

Actual behaviour
User can view annotations in every content model. In Basic Image, user can begin to create an annotation, but a popup warning indicates that the annotation will not be saved. Annotations cannot be saved in any content model.

**Comment by MarcusBarnes** [comment]
Thank you @kimpham54 for spotting this.  I've been able to confirm the behavior.

**Comment by MarcusBarnes** [comment]
Addressed in pull-request https://github.com/digitalutsc/islandora_web_annotations/pull/169 (merged with commit https://github.com/digitalutsc/islandora_web_annotations/commit/3bf0a97fb50b3d0df6eddfb0c0e656a022bd7080).
