### ISSUE TITLE
Updating newly created video annotation

### ISSUE THREAD

**Issue by Natkeeran** [digitalutsc/islandora_web_annotations#153]
Currently if the user tries to edit an annotation immediately after creating it, she/he might get an error message because the reference id may not have been returned from the server.  One option is lock lock the annotation from editing until a message is returned from the server.

**Comment by MarcusBarnes** [comment]
Initially addressed with pull-request https://github.com/digitalutsc/islandora_web_annotations/pull/158 (merged with commit https://github.com/digitalutsc/islandora_web_annotations/commit/2967ecffccefae1c742272e3c56b2adf58594430).
