### ISSUE TITLE
Enhancement Idea:  Parent and Annotation Child Management Interface in Admin

### ISSUE THREAD

**Issue by MarcusBarnes** [digitalutsc/islandora_web_annotations#157]
Recording here an idea for an enhancement.  Provide a page in the Web Annotation admin pages that for a given (parent) object PID, pulls related annotation container and annotation objects relationships and provides admin users with the ability to manage these object through this interface rather than having to log directly into Fedora commons to manage these objects.   This may help with debugging certain edge cases and also help manage annotations when access conditions for the parent object changes.

Related to this is to think about if an object + annotation container + annotations could use some of the functionality that exists for compound objects.  Using appropriate RELS-EXT relationships would likely be necessary.

**Comment by kimpham54** [comment]
Coming out of the discussion of whether or not we should delete annotations when the parent object is deleted

**Comment by MarcusBarnes** [comment]
Part of the management interface would be the ability to change the state of annotation related objects in Fedora without necessarily accessing the Fedora Admin directly.

**Comment by kstapelfeldt** [comment]
For a future release, possibly to help us manage annotation life cycle.

**Comment by kstapelfeldt** [comment]
We think that the annotation collection will address this concern sufficiently. We can always return to the issue of annotation management in a later release if we receive feedback that existing methods are too cumbersome.
