### ISSUE TITLE
Captions not displaying properly in OH when annotations is enabled

### ISSUE THREAD

**Issue by Natkeeran** [digitalutsc/islandora_web_annotations#159]
Captions are not displaying as expected in OH when annotations is enabled for OH.  

Developer Notes:
CSS/vjs-captions styling is not being properly applied.

**Comment by MarcusBarnes** [comment]
Partially addressed in pull-request https://github.com/digitalutsc/islandora_web_annotations/pull/167 (merged with commit https://github.com/digitalutsc/islandora_web_annotations/commit/079c174587cea7a11f8e2f8f937daf62ed9eca61).

**Comment by MarcusBarnes** [comment]
I'd like to suggest that we close this issue and create new (but related issues) for further adjusting how the captions are displayed when using web annotations on OH objects.

**Comment by kstapelfeldt** [comment]
@Natkeeran has a fix for the appearance but not the positioning.

**Comment by kstapelfeldt** [comment]
Closing and creating a new ticket for position of captions.
