### ISSUE TITLE
Implement Solr search of the annotations

### ISSUE THREAD

**Issue by Natkeeran** [digitalutsc/islandora_web_annotations#16]
Annotations are fedora objects with WADM Content Model.  Currently, they are being created as JsonLD data-stream with application/ld+json MIME type.  GSearch does not support indexing of application/ld+json datastreams.  We have two options:

* Change the Annotation MIME type to xml for storage purposes.  Use that for indexing.  When, retrieving, convert it back to  json-ld.
* Create a derivative xml for search purposes.

**Comment by MarcusBarnes** [comment]
Initially address in pull-request https://github.com/digitalutsc/islandora_web_annotations/pull/24 (merged with commit https://github.com/digitalutsc/islandora_web_annotations/commit/25076cfaf220cec362255750f355006c76089792).
