### ISSUE TITLE
use fedora PID (canonical uri) with web annotations

### ISSUE THREAD

**Issue by kimpham54** [digitalutsc/islandora_web_annotations#160]
Description
When Pathauto is enabled, Web Annotations is using the defined url pattern in pathauto to get retrieve and display annotations. The pathauto url alias is also written into the RELS-EXT of the annotationcontainer, as well as in the annotation under 'target' and 'context'. 

Steps to Reproduce
Enable pathauto
Generate aliases for your islandora objects
Create web annotations through the alias url for every content model
Create web annotations through the canonical url for every content model

Expected Behaviour
When I go to view web annotations through the alias url, I should be able to view all annotations I've created for that object
When I go to view web annotations through the canonical url, I should be able to view all annotations I've created for that object

Actual Behaviour
When I go to view web annotations through the alias url, I can view all of the annotations I created through the alias url
When I go to view web annotations through the canonical url, I can view all of the annotations I created through the canonical url

Notes
Actual Behaviour is confirmed for Basic Image, Video, Audio
Expected behaviour is confirmed for Large Image
Consider whether or not to store the entire url in the JSON-LD or a relative or local url, based on the W3C spec.

**Comment by MarcusBarnes** [comment]
We've been able to reproduce.  A solution is in process.  Thank you.

**Comment by MarcusBarnes** [comment]
Initially addressed in pull-request https://github.com/digitalutsc/islandora_web_annotations/pull/189 - awaiting further testing and review before it is merged.

**Comment by MarcusBarnes** [comment]
Addressed in pull-request https://github.com/digitalutsc/islandora_web_annotations/pull/189 (merged with commit e1b449182cd46cab7e1aef9ea077315750d03fda).
