### ISSUE TITLE
permissions is not respected for audio, video and oral histories

### ISSUE THREAD

**Issue by kimpham54** [digitalutsc/islandora_web_annotations#161]
Description
CRUD permissions configured through admin/people/permissions are not being respected for audio, video and oral history content models. They are being respected for basic and large image content models.

Steps to reproduce
Turn off all permissions for Islandora Web Annotations, or only enable view web annotations

Expected Behaviour
You should not be able to create web annotations

Actual Behaviour
You are still able to create web annotations in audio, video and oral history content models

**Comment by Natkeeran** [comment]
This PR partially addresses this issue: https://github.com/digitalutsc/islandora_web_annotations/commit/ecbf12268483684cf06a15749cb9bffdd5143b77

Still need to review if we need to check for user permissions in the controller.  Else, scripts may be able to post to those endpoints.

**Comment by kimpham54** [comment]
@Natkeeran https://github.com/digitalutsc/islandora_web_annotations/commit/ecbf12268483684cf06a15749cb9bffdd5143b77 was tested on video and works for all permission settings

**Comment by MarcusBarnes** [comment]
Initially addressed in pull-request https://github.com/digitalutsc/islandora_web_annotations/pull/166 (merged with commit https://github.com/digitalutsc/islandora_web_annotations/commit/f78ac04e815f7cbc65561a06b94ea3a8d05cae99).
