### ISSUE TITLE
Islandora Solr View Block

### ISSUE THREAD

**Issue by kstapelfeldt** [digitalutsc/islandora_web_annotations#171]
Challenge: A user enabling web annotations for both image and video content must disable the default annotation block (which works only for images) in order to have an annotation list for video content, or else two blocks will show on image pages. 

Approach: @kimpham54 and I determined that the best way to resolve this issue is by authoring an additional context that provides a solr view block only when content models used by the video.js player are loaded. We have exported the initial setup that is working on Kirsta's local. However, some additional documentation tasks may need to be completed, in addition to modifying the default view that is packaged with the module.

**Comment by kstapelfeldt** [comment]
@kimpham54 - how about we provide two block views with the module 1. is designed specifically for video (table view that can render html and includes start and end time and sorted by start time - dependent upon issue #162 ) and 2. is an alternative for images (ordered html view with annotations sorted by created date). We then alter the documentation to describe the packaged views and include context exports for targeting the blocks to specific content models using the machine names of the views packaged with the module. That should give people a relatively straightforward out-of-the-box experience that they can modify as needed. What do you think?

**Comment by kimpham54** [comment]
@kstapelfeldt sounds good. we will also need to update the wiki documentation afterwards with the context export

**Comment by kimpham54** [comment]
- [x] default multiple views when module is installed
- [x]  use islandora context to hide/show certain views by content model. add to documentation
- [x]  create a view for images - value, user
- [x]  add user to view block for video
- [x] render html in audio/oral history/video view

**Comment by MarcusBarnes** [comment]
Address in pull-request https://github.com/digitalutsc/islandora_web_annotations/pull/214 (merged with commit https://github.com/digitalutsc/islandora_web_annotations/commit/edf0c0fde2b29659774f8736a3be49bf821ab97e).  It would be good to include some additional documentation on how to adjust where the view blocks appear, how to hide them for basic and large image for using the default annotation list, and some comments on how they behave (for example, that the page must reload).

**Comment by kimpham54** [comment]
Documentation updated here: https://github.com/digitalutsc/islandora_web_annotations/wiki/Using-the-Islandora-Solr-View-Blocks
