### ISSUE TITLE
disable rubric in video web annotation library

### ISSUE THREAD

**Issue by kimpham54** [digitalutsc/islandora_web_annotations#174]
We do not have a use for the rubric feature included in the video web annotation library. 
Disable in https://github.com/digitalutsc/islandora_web_annotations/blob/7.x/lib/js/richText-annotator.min.js

**Comment by MarcusBarnes** [comment]
Addressed in pull-request https://github.com/digitalutsc/islandora_web_annotations/pull/182 (merged with commit https://github.com/digitalutsc/islandora_web_annotations/commit/569bc4c65a7744bf621219c17da97809189876b5).
