### ISSUE TITLE
review & cleanup WADM/Json-LD

### ISSUE THREAD

**Issue by kimpham54** [digitalutsc/islandora_web_annotations#175]
Came out of the discussion of what gets recorded when users create and update annotations. What and should get stored in 'author', 'creator', 'user', 'creator' (2nd one), 'modifiedBy'

**Comment by Natkeeran** [comment]
We have the entire annotation info from the js into the body section.  It allowed us to do rapid development.  However, this breaks validation to W3C standards.  We would have to move target related info into the target property.

Also, we have used "modifiedBy" and "pid" which are not in the context: http://www.w3.org/ns/anno.jsonld.  Thus, either we would have to adopt properties that can be substituted, or extend the context with local properties.

**Comment by kstapelfeldt** [comment]
This is large in scope, but could potentially break backwards compatibility after the module is being used as well as make it difficult to migrate later on. Maybe 8 days development? Not insignificant.

**Comment by kimpham54** [comment]
- [ ] remove body/context
- [ ] change 'pid' to canonical
- [ ] selector info, including shapes, move to target. use 'FragmentSelector'

**Comment by MarcusBarnes** [comment]
Initially addressed in pull-request https://github.com/digitalutsc/islandora_web_annotations/pull/198 (merged with commit https://github.com/digitalutsc/islandora_web_annotations/commit/60d0ed672e4d1dfb2ce4553b7accce277d7c61a5).  For other tweaks, please create specific issues to document the desired adjustments.
