### ISSUE TITLE
multiple edits annotation in video.js objects causes jsonld error

### ISSUE THREAD

**Issue by kimpham54** [digitalutsc/islandora_web_annotations#177]
**Description**
In video.js objects, editing an annotation >1 time causes errors in the WADM datastream.

**Steps to Reproduce**
Add an annotation to a video/audio/oral history.
Edit the annotation and save.
Edit the annotation again.

**Actual Behaviour**
If you have verbose messaging turned on, you should see at the end a weird jsonld response. Look at your WADM datastream and you should have a weird jsonld output (in the body it looks like the jsonld and each character in the http response was added as a value in the jsonld array).

**Expected Behaviour**
Edits to the annotation_value get stored in the body, nothing else.

**Notes/Attachments**

Normal WADM
[view.txt](https://github.com/digitalutsc/islandora_web_annotations/files/955791/view.txt)

Post-editing WADM
[annotation_197-WADM.txt](https://github.com/digitalutsc/islandora_web_annotations/files/955787/annotation_197-WADM.txt)

**Comment by MarcusBarnes** [comment]
Addressed in pull-request https://github.com/digitalutsc/islandora_web_annotations/pull/180 (merged with commit https://github.com/digitalutsc/islandora_web_annotations/commit/e8a09401cfbb5e77bf53e9650e5f76dda1c56abf).
