### ISSUE TITLE
Review using Annotorious as a plugin for AnnotatorJs

### ISSUE THREAD

**Issue by Natkeeran** [digitalutsc/islandora_web_annotations#18]
[AnnotatorJs](http://annotatorjs.org/) is a generic solution for web annotations.  Well supported projects such as [Hypothesis](https://github.com/hypothesis) use AnnotatorJs.  [Annotorious](http://annotorious.github.io/) can plugin to AnnotatorJs: http://annotorious.github.io/plug-outs/okfn-annotator.html.  

Additional features could be implemented by using Annotorious as a plugin for AnnotatorJs.  We also want to consider using Hypothesis for the front end.  This ticket is to review the pros and cons of using Annotorious as plugin for AnnotatorJs.

**Comment by kstapelfeldt** [comment]
This has been reviewed. Annotorious does not work for us at this point, and we could review it later if they do any additional development. We should review the progress later on, because @Natkeeran sees value in standardizing on a single library. Perhaps when we move to CLAW :)
