### ISSUE TITLE
Display captions at the bottom rather than the top of the screen

### ISSUE THREAD

**Issue by kstapelfeldt** [digitalutsc/islandora_web_annotations#183]
Typically, captions are expected to appear at the bottom rather than the top of the video.

**Comment by Natkeeran** [comment]
Removing the 'sites/all/modules/islandora_web_annotations/lib/css/video-js/video-js.css' => 'sites/all/modules/islandora_web_annotations/lib/css/video-js/video-js.css' from context definition seems to fix this issue.  The default video-js.css from the islandora video-js module seems to work without issue.  Needs further testing.  
      '

**Comment by kimpham54** [comment]
needs to be documented prior to release

**Comment by MarcusBarnes** [comment]
For shorter cues, the suggestion of removing 'sites/all/modules/islandora_web_annotations/lib/css/video-js/video-js.css' => 'sites/all/modules/islandora_web_annotations/lib/css/video-js/video-js.css' from context definition appears to work.  However, when there is a large amount of text in a given cue, the box containing the captions extends beyond the video block.

If a suitable solution is not available in short order, we can document this adjustment with the given caveat about long captions and continue to work on this for the next release.

**Comment by kimpham54** [comment]
@MarcusBarnes documenting sounds fine. can you create a new issue referencing this one based on your observation?

**Comment by MarcusBarnes** [comment]
Documentation at https://github.com/digitalutsc/islandora_web_annotations/wiki/Video,-Audio,-Oral-History#making-adjustments-to-the-closed-captions-position

The new issue is at https://github.com/digitalutsc/islandora_web_annotations/issues/245
