### ISSUE TITLE
Explore possibility of bundling required video.js version

### ISSUE THREAD

**Issue by kstapelfeldt** [digitalutsc/islandora_web_annotations#184]
Explore possibility of bundling required OpenSeaDragon and video.js version with custom files  (explore licensing and technical workflow). This may make it easier to install and maintain?

**Comment by MarcusBarnes** [comment]
[Islandora Web Annotations is licensed](https://github.com/digitalutsc/islandora_web_annotations#license) under GNU General Public License, version 3 or later.   [Video.js is licensed](https://github.com/videojs/video.js#license) under Apache License, Version 2.0.  According to these sources
* https://www.gnu.org/licenses/license-list.html#GPLCompatibleLicenses 
* https://www.apache.org/licenses/GPL-compatibility.html

it is possible to include Apache License, Version 2.0 software in GPL version 3 software (but not the other way around).  So for Video.js, licensing is not a hindrance for enhancing the technical installation and maintenance workflow.

**Comment by kstapelfeldt** [comment]
This enhancement would ease installation. There is a great deal of documentation in the current release to resolve this issue, though we know it is a potential stumbling block.
