### ISSUE TITLE
Overlapping blue numbers

### ISSUE THREAD

**Issue by kstapelfeldt** [digitalutsc/islandora_web_annotations#185]
As per screenshot.
<img width="172" alt="0cc29b08-fc4e-11e6-88e5-0355437107ad" src="https://cloud.githubusercontent.com/assets/467898/25665730/75d60f68-2fec-11e7-8cd6-d9d439114b61.png">

**Comment by kstapelfeldt** [comment]
Zooming would likely make the numbers appear as expected. Worth scoping. May be resolved with something like clustering. It may not be appropriate to expend this effort in the current release. Not a blocker for existing use cases.

**Comment by Natkeeran** [comment]
Currently we have simple HTML + CSS based.
Clustering type of feature would require substantial development effort (front end  and possibly backend).

**Comment by kimpham54** [comment]
noticed this issue again, in this case annotations were completely overlapping and you can't see or select the annotation behind the second annotation. see screenshot
<img width="710" alt="screen shot 2017-11-20 at 17 00 44" src="https://user-images.githubusercontent.com/2915770/33043731-6342fe9e-ce14-11e7-9e80-19dbb26479ea.png">

**Comment by kimpham54** [comment]
solution difficult to implement. detect if overlapped, move the labelling. difficult if multiple annotations overlap
possible other solution is to hover on other annotation and bring to foreground

issue will be addressed by moving around annotation windows to avoid overlapping https://github.com/digitalutsc/islandora_web_annotations/issues/236
