### ISSUE TITLE
Client Feedback: Navigation block and annotation behaviour

### ISSUE THREAD

**Issue by kstapelfeldt** [digitalutsc/islandora_web_annotations#199]
As a user I wish to read a list of annotations and if one interests me, click on a hyperlink in the list and automatically open the annotation on the object I'm viewing, in order to simplify the process of navigating to a particular annotation. Currently, I would need to find the number or start time in the interface to view a given annotation. 

![navigation-block-and-player](https://cloud.githubusercontent.com/assets/467898/26554573/d0504c70-445e-11e7-9954-bb5f88b552e9.png)

**Comment by Natkeeran** [comment]
We can implement something similar to the play segment feature in the Oral History module.  When the user clicks a button play, we can play starting from that time element.
```
document.getElementById("video-js-oh_html5_api").currentTime = 10
videojs('#video-js-oh').play()
```

More info here: https://gingertech.net/2009/08/19/jumping-to-time-offsets-in-videos/

**Comment by kstapelfeldt** [comment]
related to #186

**Comment by kstapelfeldt** [comment]
![img_20171016_140956](https://user-images.githubusercontent.com/467898/31627600-d658587a-b27b-11e7-8b01-f422b0b30221.jpg)
Summary of Discussions: We will bring back multiple results for multiple annotations. No default navigation to the annotation object view. Annotation body will be a portion of search result.
