### ISSUE TITLE
Interaction with Solr when searching for annotation_value

### ISSUE THREAD

**Issue by kimpham54** [digitalutsc/islandora_web_annotations#201]
Needs further investigation:
When you do a search for annotation_value, you get back the annotations. The annotations store the PID about annotation_parent. Is it possible to link to the PID to take you to the parent from the annotation in the search results? Next step would also involve this ticket: https://github.com/digitalutsc/islandora_web_annotations/issues/186

Or, is it better if we do a search for annotation_value, the results show the parent object (difficult to implement)

**Comment by kstapelfeldt** [comment]
We need to wireframe what would be ideal behaviour (to acceptable behaviour) and then scope.

**Comment by kstapelfeldt** [comment]
This is indexing behaviour. A substantial piece of work. Evaluate the scope and methods by which this could be done. May not be possible to add to this release.

**Comment by Natkeeran** [comment]
We had reviewed this requirement before.  Thought it seems like that Solr/Drupal views would support, we did not find any simple solutions.

**Comment by kstapelfeldt** [comment]
As there is no simple solution, we're not sure if this is better, worse or a dependency for the other Solr tickets. We are rethinking the UI of the search results for annotations and so need to discuss this in that context.

**Comment by Natkeeran** [comment]
@kimpham54 @MarcusBarnes 

Please test the  list_annotations  branch: https://github.com/digitalutsc/islandora_solr_search.  Ensure that you have annotation_parent as one of the solr fields.

**Comment by kimpham54** [comment]
needs to be documented prior to release

**Comment by MarcusBarnes** [comment]
Initial documentation provided at https://github.com/digitalutsc/islandora_web_annotations/wiki/How-to-Play-an-Audio-or-Video-Segment-when-Clicking-an-Annotation-in-Solr-Search .
