### ISSUE TITLE
Regenerating derivatives in /manage/properties

### ISSUE THREAD

**Issue by kimpham54** [digitalutsc/islandora_web_annotations#218]
Cannot do this with annotation content models, works for other Islandora content models

**Comment by kstapelfeldt** [comment]
XML may need to be regenerated. Needs to be scoped and reviewed.

**Comment by Natkeeran** [comment]
We won't usually have to do this.  Lower priority.  

Reference info: http://islandora.ca/sites/default/files/How%20to%20make%20a%20Solution%20Pack.pdf

**Comment by Natkeeran** [comment]
When the annotations WADM gets replaced, the derivative should be regenerated as well.

**Comment by MarcusBarnes** [comment]
Addressed in pull-request https://github.com/digitalutsc/islandora_web_annotations/pull/233 (merged with commit https://github.com/digitalutsc/islandora_web_annotations/commit/a65143d1c7187888fb471e23cccff4ff6d3febaa).
