### ISSUE TITLE
What should happen to annotations when the object gets deleted

### ISSUE THREAD

**Issue by Natkeeran** [digitalutsc/islandora_web_annotations#219]
Currently, when the target object is deleted, the annotations are not deleted.  We need to either document this behavior or provide a configuration option to delete all annotations and annotation container when the object gets deleted.  

Related Issue:
https://github.com/digitalutsc/islandora_web_annotations/issues/157

**Comment by kstapelfeldt** [comment]
At minimum this should be covered in relevant documentation for the release. I'm not sure that it is.

**Comment by kstapelfeldt** [comment]
Related to #221

**Comment by kimpham54** [comment]
@kstapelfeldt update documentation https://github.com/digitalutsc/islandora_web_annotations/wiki/Annotation-CRUD-Behaviour

**Comment by kstapelfeldt** [comment]
When Objects are deleted the Annotation Container retains a relationship with the default annotation collection. In this way the annotations can be accessed after an object is deleted. In a new issue we will confirm that annotation containers are also visible in the default annotation collection (Issue #229) - Kirsta to ensure this is captured in the documentation.

**Comment by kimpham54** [comment]
done
