### ISSUE TITLE
Annotations list block

### ISSUE THREAD

**Issue by Natkeeran** [digitalutsc/islandora_web_annotations#22]
Display all annotations as a list in a block or div.  A specific annotation text in the list and the cross-ponding annotation needs to be related.  

* Number the annotation boxes and the cross-ponding texts in the list
* If the user hover over a text in the list, highlight that annotation box

**Comment by MarcusBarnes** [comment]
The first bullet has been address in pull request https://github.com/digitalutsc/islandora_web_annotations/pull/26 (merged with commit https://github.com/digitalutsc/islandora_web_annotations/commit/fd746c83438e9f15aec3156c671becc771d86766).  

We are deferring work on the second bullet
* If the user hover over a text in the list, highlight that annotation box

... until we determine it is required by our users.  If it is, please create a new issue to track that feature.
