### ISSUE TITLE
Force selection of annotation namespace

### ISSUE THREAD

**Issue by kstapelfeldt** [digitalutsc/islandora_web_annotations#220]
Force selection of annotation namespace

**Comment by MarcusBarnes** [comment]
Initial work on this issue can be found in pull-request https://github.com/digitalutsc/islandora_web_annotations/pull/225.

**Comment by kstapelfeldt** [comment]
Nat to test, merge, and then reassign to Kim for testing.

**Comment by kstapelfeldt** [comment]
Go to admin page and there is no default value. A default value needs to be added. The process needs to to be documented in our wiki.

**Comment by Natkeeran** [comment]
https://github.com/digitalutsc/islandora_web_annotations/pull/228 addresses this issue to some extent.  In the case user does not set configurations, it would default to `annotation` namespace.

**Comment by Natkeeran** [comment]
Added documentation here: https://github.com/digitalutsc/islandora_web_annotations/blob/7.x/README.md
