### ISSUE TITLE
Delete AnnotationContainer does not delete Annotations

### ISSUE THREAD

**Issue by kimpham54** [digitalutsc/islandora_web_annotations#221]
Description
When I go into the AnnotationContainer object through Drupal/ Islandora and permanently remove the object, the Annotations that are part of the container are not deleted. The annotations no longer display in the original object, but are still available in the Solr View.

Steps to Reproduce
Go into an annotationcontainer, go to manage, properties, permanently remove object

Expected Behaviour
Deletes annotations in annotationcontainer

Actual Behaviour
Does not delete annotations. They are orphaned.

**Comment by MarcusBarnes** [comment]
Addressed in pull-request https://github.com/digitalutsc/islandora_web_annotations/pull/234 (merged with commit https://github.com/digitalutsc/islandora_web_annotations/commit/60509a38520fe1621b91e62dc73ca97813fbf76e).
