### ISSUE TITLE
Put AnnotationContainers into annotation collection 

### ISSUE THREAD

**Issue by kimpham54** [digitalutsc/islandora_web_annotations#229]
add collection membership to islandora:annotations_collection in rels ext in annotationcontainers so that they will be exposed in the annotation collection. This is for users to easily delete annotationcontainers

**Comment by MarcusBarnes** [comment]
Addressed in pull-request https://github.com/digitalutsc/islandora_web_annotations/pull/232 (merged with commit https://github.com/digitalutsc/islandora_web_annotations/commit/0ecbb2e16863d36237b16d63fd8e8bff697b6e1f).
