### ISSUE TITLE
Review effects of recent PR to OpenSeaDragon library

### ISSUE THREAD

**Issue by kstapelfeldt** [digitalutsc/islandora_web_annotations#231]
How does the merging of this code affect our annotation functions for large image. This issue must be resolved and then we need to review and test the remaining bugs to see if they are still relevant.

**Comment by Natkeeran** [comment]
This issue is related to open sea dragon viewer not being available in the latest version.  Created a PR in the openseadragon module to address this issue: https://github.com/Islandora/islandora_openseadragon/pull/83

**Comment by kstapelfeldt** [comment]
Not as bad as we thought. Nat has created a pull request for Open Sea Dragon. Nat will create a JIRA ticket to go with the pull request, and is in communication with Diego about this. We are expecting it will be merged, but Nat will report back.

**Comment by kstapelfeldt** [comment]
Need to update documentation after pull request is merged

**Comment by MarcusBarnes** [comment]
@Natkeeran's [pull-request](https://github.com/Islandora/islandora_openseadragon/pull/83) against [islandora_openseadragon](https://github.com/Islandora/islandora_openseadragon) was accepted and merged.   The corresponding [JIRA ticket](https://jira.duraspace.org/browse/ISLANDORA-2080) was also closed.
