### ISSUE TITLE
position issue - vertical displacement

### ISSUE THREAD

**Issue by kimpham54** [digitalutsc/islandora_web_annotations#235]
horizontal position is correct, vertical position is incorrect. 

when an annotation is created, once it gets save the positioning is not saved correctly.
y position is being displaced north by about 1.31222815 units
it is currently unclear how to reproduce this bug as it happens erratically.

![screen shot 2017-11-20 at 13 48 37](https://user-images.githubusercontent.com/2915770/33035579-ab0bce42-cdf9-11e7-9624-4e7fdb643535.png)

**Comment by MarcusBarnes** [comment]
Addressed in pull-request https://github.com/digitalutsc/islandora_web_annotations/pull/238 (merged with commit https://github.com/digitalutsc/islandora_web_annotations/commit/abe73783a2abf5fd028c1d3198e523b6bfb16766).
