### ISSUE TITLE
compatibility issue with openseadragon 2.0.0 and 7.x-1.10

### ISSUE THREAD

**Issue by kimpham54** [digitalutsc/islandora_web_annotations#239]
for the 7.x-1.10 release, there seems to be compatibility issues with openseadragon 2.0.0. when annotations is enabled, the viewer is displaced. when annotations is disabled there is only a black screen in the viewer and the image does not display.

Tested on VM 7.x-1.10 release

islandora_openseadragon for 7.x-1.10 currently uses openseadragon 2.3.1.

enabled web annotations with 2.3.1:
<img width="1072" alt="screen shot 2017-11-22 at 13 27 05" src="https://user-images.githubusercontent.com/2915770/33143754-da3af360-cf88-11e7-90af-e66a368edb68.png">

disabled web annotations with 2.0.0:

<img width="1090" alt="screen shot 2017-11-22 at 13 28 25" src="https://user-images.githubusercontent.com/2915770/33143819-105fe2e8-cf89-11e7-84fc-f05cbe6379b9.png">

enabled web annotations with 2.0.0:
<img width="1048" alt="screen shot 2017-11-22 at 13 29 43" src="https://user-images.githubusercontent.com/2915770/33143892-49995c1a-cf89-11e7-848f-ddede743c853.png">

**Comment by Natkeeran** [comment]
@kimpham54 
For 1.7.10, you will need to get latest web annotations and openseadragon module.  No need to use the specific 2.0.0 versions.  Documentation  need to be updated.

**Comment by kimpham54** [comment]
@Natkeeran I tested with 2.3.1 and still had a display issue (see above screenshot)

**Comment by Natkeeran** [comment]
@kimpham54 Hmm, ok, thanks Kim.  Will test it.

**Comment by kimpham54** [comment]
how are we going to handle the openseadragon fix? msg to rosie and diego:

We've decided that we're going to use the 7.x branch of islandora_openseadragon when we upgrade to islandora 7.x-1.10.

Issuing a patch for 7.x-1.10 is a good solution for others, and because we intend to issue a 7.x-1.10 release of the web annotations module. But as you mentioned Diego, instead of going down the patch black hole another option if web_annotations is truly the only module that's affected by this issue is that we could offer a patch, or document the modification that you'd need to make since it's only one line. Either way let me know what you decide!

**Comment by kimpham54** [comment]
needs to be documented. use 7.x branch instead of 7.x-1.10

**Comment by Natkeeran** [comment]
Updated the documentation here: https://github.com/digitalutsc/islandora_web_annotations/wiki/Large-Image
