### ISSUE TITLE
solr indexing inconsistency 

### ISSUE THREAD

**Issue by kimpham54** [digitalutsc/islandora_web_annotations#249]
The two affected plates are 5 and 6, similar to issue #248, possible related issue because it's the exact two plates that's being affected and nothing else. though the issues seem like they wouldn't be related.

Affected objects:
http://hogarth.digitalscholarship.utsc.utoronto.ca/islandora/object/hogarth%3A130
http://hogarth.digitalscholarship.utsc.utoronto.ca/islandora/object/hogarth%3A131

In the above objects, the quantity and numbering in the annotation javascript display and solr view are not the same.

See screenshot below:

<img width="1226" alt="screen shot 2018-03-08 at 14 40 59" src="https://user-images.githubusercontent.com/2915770/37172439-c4f6f0f4-22de-11e8-81d9-fa92cd24bcae.png">

**Comment by MarcusBarnes** [comment]
This issue should be addressed with the change introduced via pull-request https://github.com/digitalutsc/islandora_web_annotations/pull/250 (merged with commit https://github.com/digitalutsc/islandora_web_annotations/commit/a83e4586167445e10ae20e444b673f10fd2491fa).
