### ISSUE TITLE
Implement basic automated test converage and travis CI

### ISSUE THREAD

**Issue by Natkeeran** [digitalutsc/islandora_web_annotations#25]
Test coverage for
* CRUD operations for annotation and annotation container

**Comment by MarcusBarnes** [comment]
@Natkeeran Maybe we should break this up into smaller issues/tasks?

**Comment by kstapelfeldt** [comment]
Still working on this.

**Comment by kstapelfeldt** [comment]
A broad task that we're closing in favour of more specific task tickets to be made and associated with the next release milestone.
