### ISSUE TITLE
Create End to End/User Acceptance (manual) test plan

### ISSUE THREAD

**Issue by Natkeeran** [digitalutsc/islandora_web_annotations#27]
Create a test plan with sanity and extended test cases for manual end to end testing.  This test plan should cover range of common use cases.

A typical format for test case is as below:
* Test Case Info: #, Name/Description, System, Subsystem, Executed By, Executed Date, 
* Use Cases/Requirements Tested
* Steps
* Expected Results
* Actual Results or Pass/Fail

A sample template: https://images.template.net/wp-content/uploads/2015/12/29053639/Test-Case-Template-PDF.pdf

**Comment by kimpham54** [comment]
@Natkeeran Here's a sample test case doc I created for an Islandora release: https://docs.google.com/spreadsheets/d/1jLaTe1Bu6L0fgDCLTo9FBkl5_SaKV5hW6lBqRxMWrUE/edit?usp=sharing

**Comment by Natkeeran** [comment]
Thanks @kimpham54 .  Yes, we need something similar for the annotations module.

**Comment by Natkeeran** [comment]
## Sanity Tests

### Verify Installation
* Verify that islandora:WADMCModel and islandora:WADMContainerCModel are created in fedora after installaing the module

### CRUD Tests
* Create Annotation
* Edit Annotation
* Update Annotation
* Load Annotations
* Add then load annotations
* Load then add annotation
* Verify that Label is updated

### Permissions related Tests
* Test that CRUD operations are available as per user permissions

### Search related Tests
* Verify that you can search by value entered in an annotation

**Comment by kimpham54** [comment]
Spreadsheet to add new actions
https://docs.google.com/spreadsheets/d/1tEkMvRQdNwGREDiUOCCK4aUNFgjoor4fuAfKTrNRPHE/edit?usp=sharing

**Comment by kstapelfeldt** [comment]
Kim and I were talking and thought we wouldn't proceed further with testing until the active issues are resolved. I think we're getting closer to a standard testing spreadsheet we can package with the module for community testers helping with releases. I know Kim was still interested in exploring which of the resulting tests it makes sense to automate and how that would happen.

**Comment by kstapelfeldt** [comment]
New Testing repo created for testing docs.
