### ISSUE TITLE
Basic image - some times annotations are not loading 

### ISSUE THREAD

**Issue by Natkeeran** [digitalutsc/islandora_web_annotations#28]
Steps to reproduce:
Some times, when navigating to a basic image and click to load the annotations.  Those annotations do not get loaded.  If you refresh the page and load it, it will.  

Expected result:
It should load the basic image annotations.

**Comment by MarcusBarnes** [comment]
Addressed in pull-request https://github.com/digitalutsc/islandora_web_annotations/pull/43 (commit https://github.com/digitalutsc/islandora_web_annotations/commit/1268980d50b4cc82e651932c1262712f58648878).
