### ISSUE TITLE
How should we provide reference info in annotations?

### ISSUE THREAD

**Issue by Natkeeran** [digitalutsc/islandora_web_annotations#29]
Currently annotations are uniquely identified by PID.  Does this need to be shown in the front end so users can reference the annotations externally?

**Comment by kstapelfeldt** [comment]
@Natkeeran - Hope it's okay that I comment. I think this ties to #32 to some extent. I can see why this would be relevant to see a PID - I would say that in whatever mechanism we are using to display the annotations text (in a box) it might be valuable to be able to expose a link to the object page for management and referencing. In no case should we just print a PID (like natkeeran:21) if at all possible.

**Comment by kstapelfeldt** [comment]
Based on the discussion in our meeting today, this feature is on hold unless we discover concrete use cases and reasons for accessing the annotations discretely in this fashion.
