### ISSUE TITLE
Setting the namespace for annotations

### ISSUE THREAD

**Issue by Natkeeran** [digitalutsc/islandora_web_annotations#30]
We have to which namespace is appropriate for annotation objects.  We have 3 options:
* use default islandora namespace
* use the object's namespace (could be difficult to determine!)
* provide config option to specify a namespace

**Comment by MarcusBarnes** [comment]
Initial work on the "provide config option to specify a namespace" option in pull-request https://github.com/digitalutsc/islandora_web_annotations/pull/49 (commit https://github.com/digitalutsc/islandora_web_annotations/commit/d177513286e760dead152efbce0e1a475d2bc629).

**Comment by MarcusBarnes** [comment]
Config option could be more easily added after creation of admin form task in issue https://github.com/digitalutsc/islandora_web_annotations/issues/66.

**Comment by MarcusBarnes** [comment]
It was determined to allow admins the ability to set the namespace for annotations via the module configuration form.  Addressed in pull-request https://github.com/digitalutsc/islandora_web_annotations/pull/96  (merged with commit https://github.com/digitalutsc/islandora_web_annotations/commit/403e4654e697ded37c456766848d3e393289517e).
