### ISSUE TITLE
Feature request: indicating the parent in an Annotation object, having that be an indexable field

### ISSUE THREAD

**Issue by kimpham54** [digitalutsc/islandora_web_annotations#32]
Feature request: indicating the parent in an Annotation object, having that be an indexable field

Solr currently indexes an annotation value and annotation title (which has the parent PID listed in the title). Although the annotation currently indicates the parent, you cannot easily navigate back to the parent in the search results.

If we isolate the parent pid and index that, when we do a search for annotations we can link back to the parent by configuring the display Solr settings.

@kstapelfeldt let me know what you think of this as an additional task for development
@Natkeeran how long do you think this would take in terms of development time?

**Comment by kstapelfeldt** [comment]
As a user, I want to discover an annotation, click on the object, and be taken to the parent object. I don't think a regular user will ever want to see a standard Islandora object view for an annotation. Ideally, the annotation discovered through the search would be active on the page somehow, so the user would have a mechanism for navigating to the annotation on which they got the search result hit.

**Comment by MarcusBarnes** [comment]
Addressed in pull-request https://github.com/digitalutsc/islandora_web_annotations/pull/46 (commit https://github.com/digitalutsc/islandora_web_annotations/commit/cc16737763f510396bd2ad8c2ddaeaa8ee28694b).
