### ISSUE TITLE
Mimic HPIC Block View Layout?

### ISSUE THREAD

**Issue by kimpham54** [digitalutsc/islandora_web_annotations#33]
HPIC view has Title Team Name and Text of annotations, currently annotations are numbered and the block shows the annotations according to that number. Is it a nice to have or a necessary feature to have annotations that can be organized by Team Name? See http://digitalscholarship.utsc.utoronto.ca/projects/hpic/node/1

**Comment by kstapelfeldt** [comment]
@kimpham54 - From my perspective, is not a relevant feature now. Even in this course, Anne has moved away from the team-based approach.  It would be nice to be able to configure what data appears for each annotation in the block (similar to the way that the metadata view works) but even this, to me, is a nice-to-have and not a firm requirement.

**Comment by Natkeeran** [comment]
Closing this as  it is not a needed use case for now.
