### ISSUE TITLE
base.css font url loading from broken path

### ISSUE THREAD

**Issue by kimpham54** [digitalutsc/islandora_web_annotations#34]
Tested on 7.x-1.8 VM
`../../lib/css/hypothesis/fonts/h.woff` is being recognized as

`css/lib/css/hypothesis/fonts/h.woff
`
This works: 
`../../../lib/css/hypothesis/fonts/h.woff'`

Taken from:
http://localhost:8000/sites/all/modules/islandora_web_annotations/css//base/base.css

**Comment by MarcusBarnes** [comment]
After several attempts to reproduce unsuccessfully, I'm closing this issue.  We can reopen if someone else experiences the same behaviour.
