### ISSUE TITLE
Annotations block does not get displayed if load annotations button is not clicked

### ISSUE THREAD

**Issue by Natkeeran** [digitalutsc/islandora_web_annotations#37]
Steps to Reproduce:
* Go to a basic image
* (Don't click the load annotations button)
* Add annotations
* The annotation block does not show

Expected:
* The annotation block should show the newly added annotations.

Actual
* The annotation block does not show

**Comment by MarcusBarnes** [comment]
Addressed in pull-request https://github.com/digitalutsc/islandora_web_annotations/pull/45 (commit https://github.com/digitalutsc/islandora_web_annotations/commit/4ffdc0f8f8a6987eb5d4bc99c87ab3e3be2ab0c7).
