### ISSUE TITLE
Extend web annotatons to support Paged Content model

### ISSUE THREAD

**Issue by Natkeeran** [digitalutsc/islandora_web_annotations#40]
Paged Content model uses openseadragon viewer.  Extend web annotations to support Paged Content model.

**Comment by Natkeeran** [comment]
Just changing the context target to page content with the same config as large image works out of the box for the UI.  Each page is a separate object, thus works very similar to large image.  Some changes will be required to make it work fully.

**Comment by MarcusBarnes** [comment]
Initial documentation for Paged Content in the wiki here:  https://github.com/digitalutsc/islandora_web_annotations/wiki/Configuration:-Page-Content
