### ISSUE TITLE
Review the architecture of islandora_image_annotation

### ISSUE THREAD

**Issue by Natkeeran** [digitalutsc/islandora_web_annotations#5]
Review the architecture of islandora_image_annotation: https://github.com/Islandora-Labs/islandora_image_annotation

Is it using any annotations libraries?
Does it confirm to any annotation standard (ex WADM)?

**Comment by kstapelfeldt** [comment]
Hey! It used Shared Canvas (sorry, on my phone or I'd get a link), which implemented OAC, which was the precursor to the current Web annotation Content Model. Annotations were all stored in a single datastream, I believe. It only worked with simple images. I worked with the developer who wrote this module and may be able to fill in gaps.

**Comment by kstapelfeldt** [comment]
http://iiif.io/model/shared-canvas/1.0/

**Comment by kstapelfeldt** [comment]
https://mail.google.com/mail/u/0/?source=sync&tf=1&view=pt&th=135ede4540a91b48&search=all

**Comment by kstapelfeldt** [comment]
Sorry, wrong link on my clipboard. All the links I have now are rerouted to IIIF - I know you want to do your due diligence here, but suspect everything it used has been superceded.

**Comment by MarcusBarnes** [comment]
As we have come up with a more general approach, I'm closing this issue.  Thank you @Natkeeran for initially recording the potential source and @kstapelfeldt for chiming in with your comments and thoughts.
