### ISSUE TITLE
Video annotation position issue

### ISSUE THREAD

**Issue by Natkeeran** [digitalutsc/islandora_web_annotations#53]
When the goes over an existing annotation to edit, the edit window is shown off to the right and bottom.

**Comment by Natkeeran** [comment]
We have addressed the position issue by modifying the CSS on call back to Viewer and Editor show events.  The fixes are usable.  I'll leave the ticket open until the initial test gets completed for video annotation.

**Comment by kstapelfeldt** [comment]
This is ready for test @kimpham54 (and me)

**Comment by kstapelfeldt** [comment]
Behaviour has been good for users, so closing.
