### ISSUE TITLE
Size limit of annotation

### ISSUE THREAD

**Issue by kstapelfeldt** [digitalutsc/islandora_web_annotations#54]
If an annotation with a lot of text is created (entire first page from [here](http://veggieipsum.com/)) then the edit and delete tools become unavailable to the user. 
![screen shot 2017-01-16 at 1 50 54 pm](https://cloud.githubusercontent.com/assets/467898/21995722/5cb2fa42-dbf4-11e6-9121-12ae36bd9c9c.png)

**Comment by kstapelfeldt** [comment]
seems like we should document limits for the user somewhere, even if we create a workaround for annotations of a certain size.

**Comment by Natkeeran** [comment]
```
.annotorious-popup {
    max-height: 300px;
    overflow-y: auto;
}
```
in base.css will add a scroll when the height of the annotation box is larger than 300px.

**Comment by Natkeeran** [comment]
Created this PR to address this issue: https://github.com/digitalutsc/islandora_web_annotations/pull/63

**Comment by MarcusBarnes** [comment]
Addressed in pull-request https://github.com/digitalutsc/islandora_web_annotations/pull/63 (commit https://github.com/digitalutsc/islandora_web_annotations/commit/7b2f40538b4018432b1e527edea1ebdef8142ea9) addresses the usability.
