### ISSUE TITLE
Deleting Annotations not via the Annotations UI breaks the front end

### ISSUE THREAD

**Issue by kstapelfeldt** [digitalutsc/islandora_web_annotations#57]
If you navigate directly to an annotation using a known PID in the Drupal interface (A URL such as http://localhost:8000/islandora/object/annotation:13) and purge the object using the manage tab, you will lose the ability to view or load all other annotations from the web annotation/sea dragon interface. 

Please let me know if I can provide additional details.

**Comment by MarcusBarnes** [comment]
@kstapelfeldt @Natkeeran I've been able to confirm this behaviour.

**Comment by MarcusBarnes** [comment]
The code in pull-request https://github.com/digitalutsc/islandora_web_annotations/pull/60 (merged with commit 406899a1fa0fdf9f3b642558688d92c20ad9c280) addresses the UI breaking.   @Natkeeran  and I have some ideas on how to make sure that the annotationContainer is updated properly when purging an object using the manage object admin interface.  I suggest we keep this issue open until we've explored those ideas.  Thank you.

**Comment by MarcusBarnes** [comment]
Addressed in pull-request https://github.com/digitalutsc/islandora_web_annotations/pull/65 (commit d2d2cc9).
