### ISSUE TITLE
Can create annotation without annotation container

### ISSUE THREAD

**Issue by kstapelfeldt** [digitalutsc/islandora_web_annotations#59]
When the content models are ingested for the Web Annotation solution pack, they become available in a number of default locations (including the collection management interface). Using this, it is possible to select the content models in the collection policy and ingest objects. One can ingest an annotation without an annotation container. Explore options for removing the content models from the collection policy list. 

Let me know if you guys want more details/steps to reproduce

**Comment by kstapelfeldt** [comment]
We're going to look at addressing this in documentation and maybe talk more widely about integration with the rest of the Islandora at the conference/on lists.

**Comment by MarcusBarnes** [comment]
This has been documented in the [What is different about this module](https://github.com/digitalutsc/islandora_web_annotations#what-is-different-about-this-module) section of the project README.
