### ISSUE TITLE
Large image (openseadragon) - annotations position issue

### ISSUE THREAD

**Issue by Natkeeran** [digitalutsc/islandora_web_annotations#6]
Steps to reproduce:
1. Go to a large image page
2. Scroll down on the page
3. Create an annotation

Actual:
The annotations are positioned below the selected selection area.

Expected:
The annotations should be positioned in the selected selection area.

Developer Notes:
It appears that when the user scrolls, the annotations are placed down the image at a distance proportional to the scrolling distance.

**Comment by MarcusBarnes** [comment]
@Natkeeran provided a workaround in commit https://github.com/digitalutsc/islandora_web_annotations/commit/37e293196e8cff50b64ff976ddc52aa39699e964  We are looking for a cleaner solution.

**Comment by MarcusBarnes** [comment]
The workaround doesn't appear to work in Chrome (v54.x and v.55.x).

**Comment by MarcusBarnes** [comment]
Fix in pull-request https://github.com/digitalutsc/islandora_web_annotations/pull/52 (committed with (https://github.com/digitalutsc/islandora_web_annotations/commit/bf88ffdbbefb2b436e9a675be7c23794c4cfb0cd).
