### ISSUE TITLE
Ordering CSS/JS files

### ISSUE THREAD

**Issue by kimpham54** [digitalutsc/islandora_web_annotations#61]
Sometimes the order in which JS files are loaded are important, but indicating the order is not yet possible in Context.

Description: Experiencing interface issues if JS files for video are loaded in the order they are presented in Islandora context.
Steps to reproduce: Add context JS from modules and select all of the JS files required
Platform: php 5.5.9, islandora 7.x-1.7 on firefox and chrome
Actual: Error message that says undefined variables, like openvideoannotation and annotator, interface for video annotations does not load correctly
Expected behaviour: No error dialogs, interface loads and you're able to add annotations

This context works:

$context = new stdClass();
$context->disabled = FALSE; /* Edit this to true to make a default context disabled initially */
$context->api_version = 3;
$context->name = 'video4';
$context->description = '';
$context->tag = '';
$context->conditions = array(
 'islandora_context_condition_collection_member' => array(
   'values' => array(
     0 => TRUE,
   ),
   'options' => array(
     'islandora_collection_membership' => array(
       'islandora:audio_collection' => 'islandora:audio_collection',
       'islandora:video_collection' => 'islandora:video_collection',
       'islandora:testing1' => 'islandora:testing1',
       'islandora:entity_collection' => 0,
       'islandora:bookCollection' => 0,
       'islandora:sp_disk_image_collection' => 0,
       'islandora:newspaper_collection' => 0,
       'islandora:compound_collection' => 0,
       'islandora:sp_large_image_collection' => 0,
       'islandora:sp_web_archive_collection' => 0,
       'islandora:sp_basic_image_collection' => 0,
       'islandora:sp_pdf_collection' => 0,
       'ir:citationCollection' => 0,
       'islandora:kim' => 0,
       'crudmix:collection' => 0,
     ),
   ),
 ),
);
$context->reactions = array(
 'css_module' => array(
   'sites/all/modules/islandora_web_annotations' => array(
     'sites/all/modules/islandora_web_annotations/lib/css/video-js/video-js.css' => 'sites/all/modules/islandora_web_annotations/lib/css/video-js/video-js.css',
     'sites/all/modules/islandora_web_annotations/lib/css/annotator.min.css' => 'sites/all/modules/islandora_web_annotations/lib/css/annotator.min.css',
     'sites/all/modules/islandora_web_annotations/lib/css/ova.css' => 'sites/all/modules/islandora_web_annotations/lib/css/ova.css',
     'sites/all/modules/islandora_web_annotations/lib/css/rangeslider.min.css' => 'sites/all/modules/islandora_web_annotations/lib/css/rangeslider.min.css',
     'sites/all/modules/islandora_web_annotations/lib/css/richText-annotator.min.css' => 'sites/all/modules/islandora_web_annotations/lib/css/richText-annotator.min.css',
   ),
 ),
 'js_module' => array(
   'sites/all/modules/islandora_web_annotations' => array(
     'sites/all/modules/islandora_web_annotations/lib/js/annotator-full.min.js' => 'sites/all/modules/islandora_web_annotations/lib/js/annotator-full.min.js',
     'sites/all/modules/islandora_web_annotations/js/video/video.js' => 'sites/all/modules/islandora_web_annotations/js/video/video.js',
   ),
 ),
 'js_path' => array(
   'sites/all/modules/islandora_web_annotations/lib/js' => array(
     'sites/all/modules/islandora_web_annotations/lib/js/ova.js' => 'sites/all/modules/islandora_web_annotations/lib/js/ova.js',
     'sites/all/modules/islandora_web_annotations/lib/js/tinymce.min.js' => 'sites/all/modules/islandora_web_annotations/lib/js/tinymce.min.js',
     'sites/all/modules/islandora_web_annotations/lib/js/richText-annotator.min.js' => 'sites/all/modules/islandora_web_annotations/lib/js/richText-annotator.min.js',
     'sites/all/modules/islandora_web_annotations/lib/js/rangeslider.min.js' => 'sites/all/modules/islandora_web_annotations/lib/js/rangeslider.min.js',
   ),
 ),
);
$context->condition_mode = 0;

File path to add: sites/all/modules/islandora_web_annotations/lib/js

**Comment by Natkeeran** [comment]
We are handling this issue with a workaround.  In the context module, it allows for assets to be loaded in different ways, i.e from module and from a file path.  Both are stacked in sequence.  Thus, we are making use of this to order the js.  Though not an ideal solution, it is a sufficient solution for now.  We don't want to make any changes to the Drupal modules.
