### ISSUE TITLE
Admin Form: Debug Flag for Verbose Messages

### ISSUE THREAD

**Issue by MarcusBarnes** [digitalutsc/islandora_web_annotations#66]
Tasks:

1.  Create admin form
2.  Provide option for a verbose (debug) notification text that will include verbose output for confirmation messages.  Default to simple, non-verbose messages.
3. Check for flag and change alert box text on annotation creation, save (and edit) appropriately.

**Comment by Natkeeran** [comment]
This PR addresses this issue: https://github.com/digitalutsc/islandora_web_annotations/pull/78
