### ISSUE TITLE
Admin Form:  Large Image - Add remove box around label at specific zoom level

### ISSUE THREAD

**Issue by MarcusBarnes** [digitalutsc/islandora_web_annotations#67]
Add a content model specific configuration section to the admin form.

For large image, add a configuration option to record a zoom level at which to hide the blue box and or label (value strictly between 0 and 1). Default would be to keep the blue box and label.

Depends on creation of admin form step in issue https://github.com/digitalutsc/islandora_web_annotations/issues/66.

**Comment by kstapelfeldt** [comment]
Addressed with the pull request that implemented number scaling.
