### ISSUE TITLE
Create interfaces for annotation and annotationConatiner

### ISSUE THREAD

**Issue by Natkeeran** [digitalutsc/islandora_web_annotations#7]
Create php interfaces that confirms to [Web Annotation Protocol](https://www.w3.org/TR/annotation-protocol/#bib-annotation-model) to do CRUD operations.

* interfaceAnnotation
* interfaceAnnotationContainer

**Comment by MarcusBarnes** [comment]
Initial work:

* interfaceAnnotation: https://github.com/digitalutsc/islandora_web_annotations/blob/master/includes/interfaceAnnotation.php

* interfaceAnnotationContainer: https://github.com/digitalutsc/islandora_web_annotations/blob/master/includes/interfaceAnnotationContainer.php
