### ISSUE TITLE
Blue Box surrounding number fails to scale?

### ISSUE THREAD

**Issue by kstapelfeldt** [digitalutsc/islandora_web_annotations#71]
Created an annotation and blue box with number exceeds box drawn for annotation. Firefox 50.1.0. Seems to happen when an annotation is created with the image zoomed. All the blue boxes seem to be the same size. 
<img width="543" alt="screen shot 2017-01-23 at 12 36 29 pm" src="https://cloud.githubusercontent.com/assets/467898/22215355/0b41c83a-e169-11e6-9601-7493138d5b51.png">

<img width="425" alt="screen shot 2017-01-23 at 12 40 08 pm" src="https://cloud.githubusercontent.com/assets/467898/22215377/27490624-e169-11e6-94ed-447df82f0f40.png">

**Comment by MarcusBarnes** [comment]
This issue is related to https://github.com/digitalutsc/islandora_web_annotations/issues/68.

**Comment by kimpham54** [comment]
if the blue box scaled to the size of the annotation area you could potentially get very small blue boxes where you can’t read the number of the annotation. One option is that instead of having the blue box inside the annotation area, it can be adjacent to it?

**Comment by MarcusBarnes** [comment]
@kimpham54 That's a good suggestion.  We can explore that when working on issue #68.

**Comment by kstapelfeldt** [comment]
@kimpham54 +1

**Comment by MarcusBarnes** [comment]
Update - this issue was addressed with the merging of the code in pull-request https://github.com/digitalutsc/islandora_web_annotations/pull/92.  We are temporarily leaving the issue open until we review the other ideas put forth in the comments above.  Thank you.

**Comment by kstapelfeldt** [comment]
I am totally satisfied with the new scaling functionality and will close this for now. @kimpham54 let me know if you think opacity is required.

**Comment by kstapelfeldt** [comment]
<img width="568" alt="screen shot 2017-01-26 at 3 24 07 pm" src="https://cloud.githubusercontent.com/assets/467898/23344639/edf6f20a-fc4d-11e6-8861-758f68e63e65.png">
To discuss!

**Comment by kstapelfeldt** [comment]
<img width="172" alt="screen shot 2017-02-26 at 6 02 09 pm" src="https://cloud.githubusercontent.com/assets/467898/23344643/0cc29b08-fc4e-11e6-88e5-0355437107ad.png">
To discuss - what should we do with overlapping numbers?

**Comment by kstapelfeldt** [comment]
Closing and opening new issue for overlapping numbers
