### ISSUE TITLE
Base.js:  AJAX url needs to be updated

### ISSUE THREAD

**Issue by MarcusBarnes** [digitalutsc/islandora_web_annotations#72]
The URL parameter in the AJAX calls in base.js needs to be updated so as to not assume localhost as the domain.   For example, see https://github.com/digitalutsc/islandora_web_annotations/blob/master/js/base/base.js#L242.

**Comment by Natkeeran** [comment]
This PR https://github.com/digitalutsc/islandora_web_annotations/pull/74 address this issue.  Thank you Marcus.
