### ISSUE TITLE
Documentation: JSON-LD content format

### ISSUE THREAD

**Issue by kimpham54** [digitalutsc/islandora_web_annotations#79]
add to wiki documentation a sample of what a complete, all properties populated JSON-LD datastreams for both WADMAnnotationContainer and WADMAnnotation would look like

**Comment by kimpham54** [comment]
https://github.com/digitalutsc/islandora_web_annotations/wiki/Metadata-Spec to update

**Comment by kstapelfeldt** [comment]
duplicates #175
