### ISSUE TITLE
Add metadata for video annotations

### ISSUE THREAD

**Issue by Natkeeran** [digitalutsc/islandora_web_annotations#83]
The video annotations do not have accurate metadata information (user, creation date etc).  This metadata needs to be added within the json-ld structure we use.

**Comment by MarcusBarnes** [comment]
Addressed in pull-request https://github.com/digitalutsc/islandora_web_annotations/pull/89 (merged with https://github.com/digitalutsc/islandora_web_annotations/commit/8c0b25cd8afdd9c2a4a0c8a5f3806f66e237aea3).
