### ISSUE TITLE
Turning off the dialog box after an annotation is created

### ISSUE THREAD

**Issue by kimpham54** [digitalutsc/islandora_web_annotations#86]
We don't need to have a dialog box once an annotation is created - I think it's an extra unncessary confirmation step that will hinder someone's workflow. Thoughts @kstapelfeldt ?

**Comment by MarcusBarnes** [comment]
If the above behavior suggested above is desirable, we can choose to include the success dialog boxes only when Verbose Alert Messages setting is checked in the Islandora Web Annotations admin settings.

**Comment by kimpham54** [comment]
@MarcusBarnes agreed. I think in the verbose alert messages should include the content of the annotation that's being created
