### ISSUE TITLE
Implement update, delete annotation in the backend

### ISSUE THREAD

**Issue by Natkeeran** [digitalutsc/islandora_web_annotations#9]
Enable the user to update a single annotation.  Save the changes to fedora.  
Enable the user to delete a single annotation.  Save the changes to fedora.

**Comment by MarcusBarnes** [comment]
Initial work on this addressed in pull-request https://github.com/digitalutsc/islandora_web_annotations/pull/14 (merged into master with commit https://github.com/digitalutsc/islandora_web_annotations/commit/82e032b4c603075cb95b055d5b3f7e2b20fa63b4).  Please create further more specific issues for further refinements and functionality.
