### ISSUE TITLE
Add the annotations' time info to solr indexing for video annotations

### ISSUE THREAD

**Issue by Natkeeran** [digitalutsc/islandora_web_annotations#93]
Add the annotations' time info to solr indexing for video annotations.  Adding the time info to solr indexing for videos will provide the solr view designer.

**Comment by MarcusBarnes** [comment]
Initially addressed in pull-request https://github.com/digitalutsc/islandora_web_annotations/pull/94 (merged with https://github.com/digitalutsc/islandora_web_annotations/commit/e492d6f004dca9dc9d0684ee147a3f5a5313439a).
